github: [your-github-username]
patreon: [your-patreon-username]
open_collective: [your-open-collective-username]
ko_fi: [your-ko-fi-username]
buy_me_a_coffee: [your-buy-me-a-coffee-username]
liberapay: [your-liberapay-username]
issuehunt: [your-issuehunt-username]
otechie: [your-otechie-username]
custom: ['https://your-custom-url.com']
