name: Automate Issues

on:
  workflow_dispatch:
  issues:
    types: [opened]

permissions:
  issues: write   # Allows the action to create issues
  contents: read  # Allows the action to checkout the repository contents

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Create Issue
        run: |
          echo "This is a test to see if the workflow runs correctly."
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d '{"title":"New Issue","body":"This issue was automatically created using the ISSUES_TEMPLATE.","labels":["automated"]}'